author:
  name: "duck"

baseURL: "https://qua3k.github.io/"
languageCode: "en-us"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
  - identifier: about
    name: About   
    url: /about/

theme: "tale-hugo"
title: "duck's pond"
