baseURL = "https://qua3k.github.io/"
languageCode = "en-us"
theme = "blog-theme"
title = "duck's pond"

[author]
name = "duck (@qua3k) — Security Engineer "

[markup]
  [markup.goldmark.renderer]
  unsafe = true

[params]
description = "hi i'm a duck and these are my ramblings"