Authors = ["duck"]
baseURL = "https://qua3k.github.io/"
languageCode = "en-us"
theme = "new-theme"
title = "segmentation fault"

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNumbersInTable = true
    noClasses = false
    style = 'github'
    tabWidth = 4


[params]
  description = "hi i'm a duck and these are my ramblings"
  listUrl = "/posts-list/"
