baseURL = "https://qua3k.github.io/"
languageCode = "en-us"
theme = "blog-theme"
title = "duck's pond"

[author]
  name = "duck"
  url = "https://github.com/qua3k"
  username = "qua3k"

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2


[params]
  description = "hi i'm a duck and these are my ramblings"
  listUrl = "/posts-list/"